name: upi_analyzer
description: AI-powered UPI transaction analyzer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.3.3
  path: ^1.9.0

  upi_sms_parser: ^0.1.0

  flutter_sms_inbox: ^1.0.3

  # BLoC - state management (your Redux equivalent)
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5        # Makes comparing BLoC states easy

  # Navigation
  go_router: ^13.0.0       # Like React Router

  # Charts (for insights screen)
  fl_chart: ^0.68.0

  # Icons
  iconsax_flutter: ^1.0.1  # The icon style matching your UI

  # Permissions (for SMS)
  permission_handler: ^11.3.1

  # Local storage
  shared_preferences: ^2.2.3  # Like localStorage for Android

  # File system access (for CSV export)
  path_provider: ^2.1.2

  # Networking (for calling AI provider APIs from ChatBloc)
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true